// SPDX-License-Identifier: ISC
//
// Callback/time/control test, exercised exactly the way cocotb drives a VPI
// simulator (no cocotb process needed):
//
//   * the clock is generated by a self-re-registering cbAfterDelay timer,
//   * an input (rst) is driven by a one-shot cbAfterDelay,
//   * an output (count) is observed via cbValueChange,
//   * the run is ended with vpi_control(vpiFinish) from a timer.
//
// It asserts the observed values increment once reset is released, that they
// were sampled at the expected simulation times, and that vpi_get_time tracks.

#include <cstdio>
#include <cstring>
#include <vector>

#include <vpi_user.h>

#include "cxxrtl_vpi/model.h"
#include "cxxrtl_vpi/sim.h"

namespace {

vpiHandle clk, rst, count;
const uint64_t HALF = 5;     // half clock period (sim time units)
const uint64_t RST_OFF = 23; // release reset between posedges
const uint64_t FINISH = 100;

std::vector<int> samples;       // count values observed, with their times
std::vector<uint64_t> sample_t;

void put_int(vpiHandle h, int v) {
    s_vpi_value val;
    val.format = vpiIntVal;
    val.value.integer = v;
    vpi_put_value(h, &val, nullptr, vpiNoDelay);
}

int get_int(vpiHandle h) {
    s_vpi_value val;
    val.format = vpiIntVal;
    vpi_get_value(h, &val);
    return val.value.integer;
}

uint64_t now() {
    s_vpi_time t;
    t.type = vpiSimTime;
    vpi_get_time(nullptr, &t);
    return (static_cast<uint64_t>(t.high) << 32) | t.low;
}

void schedule(PLI_INT32 (*fn)(p_cb_data), uint64_t delay) {
    s_vpi_time t;
    t.type = vpiSimTime;
    t.high = static_cast<PLI_UINT32>(delay >> 32);
    t.low = static_cast<PLI_UINT32>(delay & 0xffffffffu);
    s_cb_data cb;
    std::memset(&cb, 0, sizeof(cb));
    cb.reason = cbAfterDelay;
    cb.cb_rtn = fn;
    cb.time = &t;
    vpi_register_cb(&cb);
}

PLI_INT32 clock_cb(p_cb_data) {
    put_int(clk, !get_int(clk));   // toggle
    schedule(clock_cb, HALF);      // re-arm (cocotb's clock pattern)
    return 0;
}

PLI_INT32 rst_off_cb(p_cb_data) {
    put_int(rst, 0);
    return 0;
}

PLI_INT32 finish_cb(p_cb_data) {
    vpi_control(vpiFinish);
    return 0;
}

PLI_INT32 count_changed_cb(p_cb_data) {
    samples.push_back(get_int(count));
    sample_t.push_back(now());
    return 0;
}

}  // namespace

int main() {
    cxxrtl_vpi::Model model;
    model.create();
    cxxrtl_vpi::vpi_provider_bind(&model);

    clk = vpi_handle_by_name((PLI_BYTE8 *)"clk", nullptr);
    rst = vpi_handle_by_name((PLI_BYTE8 *)"rst", nullptr);
    count = vpi_handle_by_name((PLI_BYTE8 *)"count", nullptr);
    if (!clk || !rst || !count) {
        printf("FAIL: handle resolution\n");
        return 1;
    }

    // Initial input state, then schedule stimulus the way cocotb would.
    put_int(rst, 1);
    put_int(clk, 0);

    s_cb_data vc;
    std::memset(&vc, 0, sizeof(vc));
    vc.reason = cbValueChange;
    vc.cb_rtn = count_changed_cb;
    vc.obj = count;
    vpi_register_cb(&vc);

    schedule(clock_cb, HALF);
    schedule(rst_off_cb, RST_OFF);
    schedule(finish_cb, FINISH);

    cxxrtl_vpi::simulate(model);

    // ---- checks ----
    printf("== observed count changes ==\n");
    for (size_t i = 0; i < samples.size(); i++)
        printf("  t=%llu count=%d\n", (unsigned long long)sample_t[i], samples[i]);

    if (samples.empty()) {
        printf("FAIL: no value-change callbacks fired\n");
        return 1;
    }
    // After reset releases, the counter must increment by 1 each posedge.
    for (size_t i = 0; i < samples.size(); i++) {
        if (samples[i] != static_cast<int>(i + 1)) {
            printf("FAIL: sample %zu = %d, expected %zu\n", i, samples[i], i + 1);
            return 1;
        }
    }
    // Posedges land at t = 25, 35, 45, ... (clk rises at 5,15,25,...; counting
    // starts once rst is low at t=23). Check the cadence.
    for (size_t i = 0; i < sample_t.size(); i++) {
        uint64_t expect = 25 + 10 * i;
        if (sample_t[i] != expect) {
            printf("FAIL: sample %zu at t=%llu, expected t=%llu\n", i,
                   (unsigned long long)sample_t[i], (unsigned long long)expect);
            return 1;
        }
    }
    printf("SUCCESS (%zu posedge samples, 1..%d)\n", samples.size(),
           (int)samples.size());
    return 0;
}
